#!/bin/bash

_lvk=$(wget -qO- https://raw.githubusercontent.com/vxu007/vxu/main/Syst/ver)
IP=$(wget -qO- ipv4.icanhazip.com)
IP2=$(wget -qO- http://whatismyip.akamai.com/)
[[ "$IP" != "$IP2" ]] && ipdovps="$IP2" || ipdovps="$IP"
mkdir -p /etc/vxu
echo -e "$ipdovps" >/etc/vxu/IP
lst=$1 && lst1=$2 && lst2=$3 && key1=$4 && key2=crz
echo -e "America/Sao_Paulo" >/etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime >/dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata >/dev/null 2>&1
[[ -z $lst1 ]] && {
	rm -rf $_Ink/list >/dev/null 2>&1 && cat /dev/null >~/.bash_history && history -c && exit 0
}
[[ ! -d /etc/vxu ]] && mkdir /etc/vxu
[[ ! -d /etc/vxu/passwds ]] && mkdir /etc/vxu/passwds
[[ ! -e /etc/vxu/Exp ]] && touch /etc/vxu/Exp
[[ ! -d /etc/vxu/.tmp ]] && mkdir /etc/vxu/.tmp
echo -e 'by: @voltsshx' >/usr/lib/voltx && cat /usr/lib/voltx >$lst2/licence && cat /usr/lib/voltx > /etc/vxu/.tmp/vps
netstat -nplt | grep -w 'apache2' | grep -w '80' && sed -i "s/Listen 80/Listen 8888/g" /etc/apache2/ports.conf && service apache2 restart
[[ "$(grep -o '#Port 22' /etc/ssh/sshd_config)" == "#Port 22" ]] && sed -i "s;#Port 22;Port 22;" /etc/ssh/sshd_config && service ssh restart
grep -v "^PasswordAuthentication" /etc/ssh/sshd_config >/tmp/passlogin && mv /tmp/passlogin /etc/ssh/sshd_config
echo "PasswordAuthentication yes" >>/etc/ssh/sshd_config
_dir1='/bin'
_dir2='/etc/vxu'
_dir3='/root'
rm $_dir2/open.py $_dir2/proxy.py $_dir2/wsproxy.py >/dev/null 2>&1
_mdls=("burn" "blockt" "bnrvps" "change_pass" "connection" "create_user" "droplimiter" "expcleaner" "infousers" "instsqd" "limiter" "menu" "online_accounts" "open.py" "otimizar" "proxy.py" "remove_user" "renew_user" "restartservice" "restartvps" "senharoot" "speedtest" "tcp_bbr" "udpgw" "uexpired" "uninstall" "user_limits" "userbackup" "vps_info" "wsproxy.py")
_mdls2=("active.sh")
for _arq in ${_mdls[@]}; do
	[[ -e $_dir1/$_arq ]] && rm $_dir1/$_arq >/dev/null 2>&1
	wget -c -P $_dir1 https://raw.githubusercontent.com/vxu007/vxu/main/funcs/$_arq
	chmod +x $_dir1/$_arq
done
for _arq in ${_mdls2[@]}; do
	[[ -e $_dir3/$_arq ]] && rm $_dir3/$_arq >/dev/null 2>&1
	wget -c -P $_dir3 https://raw.githubusercontent.com/vxu007/vxu/main/funcs/$_arq
	chmod +x $_dir3/$_arq
done
cd /var/www/html && mkdir server
cd /root && ./active.sh
mv $_dir1/open.py $_dir1/proxy.py $_dir1/wsproxy.py $_dir2
_arq_host="/etc/hosts"
_host[0]="/vxu?"
for host in ${_host[@]}; do
	if [[ "$(grep -w "$host" $_arq_host | wc -l)" = "0" ]]; then
		sed -i "3i\127.0.0.1 $host" $_arq_host
	fi
done
[[ ! -e /etc/autostart ]] && {
	echo '#!/bin/bash
clear
#Auto Start' >/etc/autostart
	chmod +x /etc/autostart
} ||  {
	screen -wipe >/dev/null
	echo '#!/bin/bash
clear

#AutoStart' >/etc/autostart
	chmod +x /etc/autostart
}
crontab -r >/dev/null 2>&1
(
	crontab -l 2>/dev/null
	echo "@daily /bin/verifatt"
	echo "@reboot /etc/autostart"
	echo "* * * * * /etc/autostart"
	echo "0 */6 * * * /bin/uexpired"
	echo "*/1 * * * * cd /root/ && ./active.sh"
) | crontab -
echo "$_lvk" | sed -n '1 p' | cut -d' ' -f2 >/bin/ver && cat /bin/ver >/home/voltx
# wget https://github.com/vxu007/vxu/raw/main/blob/jq-linux64 >/dev/null 2>&1
# chmod +x jq-linux64 && mv jq-linux64 $(which jq)
service cron restart >/dev/null 2>&1
service ssh restart >/dev/null 2>&1
[[ -d /var/www/html/openvpn ]] && service apache2 restart >/dev/null 2>&1
rm -rf $lst1/list >/dev/null 2>&1
